ItemEvents.tooltip(event => {

    event.add('minecraft:brown_mushroom', Text.yellow('Boletus Edulis'))
    event.add('minecraft:red_mushroom', Text.yellow('Amanita Muscaria'))
    event.add('minecraft:bamboo', Text.yellow('Bambusoideae'))
    event.add('minecraft:sugar_cane', Text.yellow('Saccharum'))
    event.add('minecraft:cactus', Text.yellow('Cactaceae'))
    event.add('minecraft:wheat_seeds', Text.yellow('Triticum'))
    event.add('minecraft:cocoa_beans', Text.yellow('Theobroma Cacao'))
    event.add('minecraft:pumpkin_seeds', Text.yellow('Cucurbita'))
    event.add('minecraft:melon_seeds', Text.yellow('Citrullus'))
    event.add('minecraft:beetroot_seeds', Text.yellow('Beta Vulgaris'))
    event.add('minecraft:torchflower_seeds', Text.yellow('Etlingera Elatior'))
    event.add('minecraft:glow_berries', Text.yellow('Glow Malinae'))
    event.add('minecraft:sweet_berries', Text.yellow('Synsepalum Dulcificum'))
    event.add('minecraft:nether_wart', Text.yellow('Nether Malinae'))
    event.add('minecraft:kelp', Text.yellow('Laminariales'))
    event.add('minecraft:sea_pickle', Text.yellow('Salicornia'))
    event.add('minecraft:chorus_plant', Text.yellow('Chorus Musa'))
    event.add('minecraft:carrot', Text.yellow('Daucus Carota'))
    event.add('minecraft:apple', Text.yellow('Malus Domestica'))
    event.add('minecraft:potato', Text.yellow('Solanum Tuberosum'))

    event.add('farmersdelight:onion', Text.yellow('Allium Cepa'))
    event.add('farmersdelight:tomato_seeds', Text.yellow('Solanum lycopersicum'))
    event.add('farmersdelight:rice', Text.yellow('Oryza sativa'))
    event.add('farmersdelight:cabbage_seeds', Text.yellow('Brassica oleracea var. capitat'))
})