ClientEvents.lang('en_us', event => {
  event.renameItem('biomesoplenty:fir_sapling', 'European Fir Sapling')
  event.renameItem('biomesoplenty:fir_leaves', 'European Fir Leaves')
  event.renameItem('biomesoplenty:fir_log', 'European Fir Log')
  event.renameItem('biomesoplenty:stripped_fir_log', 'Stripped European Fir Log')
  event.renameItem('biomesoplenty:fir_wood', 'European Fir Wood')
  event.renameItem('biomesoplenty:stripped_fir_wood', 'Stripped European Fir Wood')
  event.renameItem('biomesoplenty:fir_planks', 'European Fir Planks')
  event.renameItem('biomesoplenty:fir_slab', 'European Fir slab')
  event.renameItem('biomesoplenty:fir_stairs', 'European Fir Stairs')
  event.renameItem('biomesoplenty:fir_fence', 'European Fir Fence')
  event.renameItem('biomesoplenty:fir_fence_gate', 'European Fir Fence Gate')
  event.renameItem('biomesoplenty:fir_door', 'European Fir Door')
  event.renameItem('biomesoplenty:fir_trapdoor', 'European Fir Trapdoor')
  event.renameItem('biomesoplenty:fir_pressure_plate', 'European Fir Pressure Plate')
  event.renameItem('biomesoplenty:fir_button', 'European Fir Button')
  event.renameItem('biomesoplenty:fir_sign', 'European Fir Sign')
  event.renameItem('biomesoplenty:fir_hanging_sign', 'European Fir Hanging Sign')
  event.renameItem('biomesoplenty:fir_boat', 'European Fir Boat')
  event.renameItem('biomesoplenty:fir_chest_boat', 'European Fir Boat with Chest')
})