ItemEvents.tooltip(event => {

    event.add('minecraft:oak_sapling', Text.yellow('Quercus'))
    event.add('minecraft:spruce_sapling', Text.yellow('Picea'))
    event.add('minecraft:birch_sapling', Text.yellow('Betula'))
    event.add('minecraft:jungle_sapling', Text.yellow('Ceiba'))
    event.add('minecraft:acacia_sapling', Text.yellow('Acacia'))
    event.add('minecraft:dark_oak_sapling', Text.yellow('Quercus Velutina'))
    event.add('minecraft:cherry_sapling', Text.yellow('Prunus Cerasus'))
    event.add('minecraft:crimson_fungus', Text.yellow('Crimson Fungus'))
    event.add('minecraft:warped_fungus', Text.yellow('Warped Fungus'))
    event.add('minecraft:mangrove_propagule', Text.yellow('Mangrovum'))

    //Let's do Blooming Nature
    event.add('bloomingnature:larch_sapling', Text.yellow('Larix'))
    event.add('bloomingnature:baobab_sapling', Text.yellow('Adansonia'))
    event.add('bloomingnature:aspen_sapling', Text.yellow('Populus tremuloides'))
    event.add('bloomingnature:swamp_oak_sapling', Text.yellow('Quercus palustris'))
    event.add('bloomingnature:swamp_cypress_sapling', Text.yellow('Taxodium distichum'))
    event.add('bloomingnature:ebony_sapling', Text.yellow('Diospyros'))
    event.add('bloomingnature:chestnut_sapling', Text.yellow('Castanea'))
    event.add('bloomingnature:fir_sapling', Text.yellow('Abies'))
    event.add('bloomingnature:fan_palm_sprout', Text.yellow('Livistona'))

    //biomes o plenty
    event.add('biomesoplenty:fir_sapling', Text.yellow('Abies alba'))
    event.add('biomesoplenty:origin_sapling', Text.yellow('Arbor'))
    event.add('biomesoplenty:magic_sapling', Text.yellow('Arbor Magica'))
    event.add('biomesoplenty:dead_sapling', Text.yellow('Arbor Mortuus'))
    event.add('biomesoplenty:rainbow_birch_sapling', Text.yellow('Eucalyptus Degluptia'))
    event.add('biomesoplenty:orange_autumn_sapling', Text.yellow('Liquidambar Styraciflua'))
    event.add('biomesoplenty:yellow_autumn_sapling', Text.yellow('Liriodendron Tulipifera'))
    event.add('biomesoplenty:hellbark_sapling', Text.yellow('Melaleuca Quinquenervia'))
    event.add('biomesoplenty:flowering_oak_sapling', Text.yellow('Quercus Robur'))
    event.add('biomesoplenty:snowblossom_sapling', Text.yellow('Styrax Japonicus'))
    event.add('biomesoplenty:umbran_sapling', Text.yellow('Umbra Arboris'))

    //oh the biomes we've gone
    event.add('biomeswevegone:ironwood_sapling', Text.yellow('Ostrya virginiana'))
    event.add('biomeswevegone:maple_sapling', Text.yellow('Acer'))
    event.add('biomeswevegone:red_maple_sapling', Text.yellow('Acer rubrum'))
    event.add('biomeswevegone:silver_maple_sapling', Text.yellow('Acer saccharinum'))
    event.add('biomeswevegone:araucaria_sapling', Text.yellow('Araucaria araucana'))
    event.add('biomeswevegone:palm_sapling', Text.yellow('Arecaceae'))
    event.add('biomeswevegone:yellow_birch_sapling', Text.yellow('Betula alleghaniensis'))
    event.add('biomeswevegone:red_birch_sapling', Text.yellow('Betula occidentalis'))
    event.add('biomeswevegone:orange_birch_sapling', Text.yellow('Betula utilis'))
    event.add('biomeswevegone:cika_sapling', Text.yellow('Catalpa bignonioides'))
    event.add('biomeswevegone:cypress_sapling', Text.yellow('Cupressaceae'))
    event.add('biomeswevegone:rainbow_eucalyptus_sapling', Text.yellow('Eucalyptus deglupta'))
    event.add('biomeswevegone:witch_hazel_sapling', Text.yellow('Hamamelis virginiana'))
    event.add('biomeswevegone:brown_oak_sapling', Text.yellow('Helicia glabriflora'))
    event.add('biomeswevegone:blue_enchanted_sapling', Text.yellow('Hyacinthoides non-scripta'))
    event.add('biomeswevegone:holly_sapling', Text.yellow('Ilex aquifolium'))
    event.add('biomeswevegone:white_sakura_sapling', Text.yellow('Izu Oshima Cherry'))
    event.add('biomeswevegone:jacaranda_sapling', Text.yellow('Jacaranda'))
    event.add('biomeswevegone:indigo_jacaranda_sapling', Text.yellow('Jacaranda mimosifolia'))
    event.add('biomeswevegone:white_mangrove_sapling', Text.yellow('Laguncularia'))
    event.add('biomeswevegone:orchard_sapling', Text.yellow('Malus pumila'))
    event.add('biomeswevegone:palo_verde_sapling', Text.yellow('Parkinsonia'))
    event.add('biomeswevegone:orange_spruce_sapling', Text.yellow('Picea aurantiaca'))
    event.add('biomeswevegone:blue_spruce_sapling', Text.yellow('Picea pungens'))
    event.add('biomeswevegone:blue_spruce_sapling', Text.yellow('Picea pungens'))
    event.add('biomeswevegone:red_spruce_sapling', Text.yellow('Picea rubens'))
    event.add('biomeswevegone:yellow_spruce_sapling', Text.yellow('Picea sitchensis \'Aurea'))
    event.add('biomeswevegone:pine_sapling', Text.yellow('Pinus jeffreyi'))
    event.add('biomeswevegone:yellow_sakura_sapling', Text.yellow('Prunus serrulata \'Ukon\''))
    event.add('biomeswevegone:orange_oak_sapling', Text.yellow('Quercus coccinea'))
    event.add('biomeswevegone:red_oak_sapling', Text.yellow('Quercus rubra'))
    event.add('biomeswevegone:willow_sapling', Text.yellow('Salix'))
    event.add('biomeswevegone:brown_birch_sapling', Text.yellow('Scolopia braunii'))
    event.add('biomeswevegone:redwood_sapling', Text.yellow('Sequoioideae'))
    event.add('biomeswevegone:green_enchanted_sapling', Text.yellow('Silva Magica Viridis'))
    event.add('biomeswevegone:mahogany_sapling', Text.yellow('Swietenia'))
    event.add('biomeswevegone:skyris_sapling', Text.yellow('xyris'))
    event.add('biomeswevegone:yucca_sapling', Text.yellow('Yucca'))
    event.add('biomeswevegone:zelkova_sapling', Text.yellow('Zelkova serrata'))
    event.add('biomeswevegone:brown_zelkova_sapling', Text.yellow('Zelkova serrata Makino'))

    //regions unexplored
    event.add('regions_unexplored:blackwood_sapling', Text.yellow('Acacia melanoxylon'))
})