ItemEvents.tooltip(event => {

    event.add('minecraft:oak_sapling', Text.yellow('Quercus'))
    event.add('minecraft:spruce_sapling', Text.yellow('Picea'))
    event.add('minecraft:birch_sapling', Text.yellow('Betula'))
    event.add('minecraft:jungle_sapling', Text.yellow('Ceiba'))
    event.add('minecraft:acacia_sapling', Text.yellow('Acacia'))
    event.add('minecraft:dark_oak_sapling', Text.yellow('Quercus Velutina'))
    event.add('minecraft:cherry_sapling', Text.yellow('Prunus Cerasus'))
    event.add('minecraft:crimson_fungus', Text.yellow('Crimson Fungus'))
    event.add('minecraft:warped_fungus', Text.yellow('Warped Fungus'))
    event.add('minecraft:mangrove_propagule', Text.yellow('Mangrovum'))

    //Let's do Blooming Nature
    event.add('bloomingnature:larch_sapling', Text.yellow('Larix'))
    event.add('bloomingnature:baobab_sapling', Text.yellow('Adansonia'))
    event.add('bloomingnature:aspen_sapling', Text.yellow('Populus tremuloides'))
    event.add('bloomingnature:swamp_oak_sapling', Text.yellow('Quercus palustris'))
    event.add('bloomingnature:swamp_cypress_sapling', Text.yellow('Taxodium distichum'))
    event.add('bloomingnature:ebony_sapling', Text.yellow('Diospyros'))
    event.add('bloomingnature:chestnut_sapling', Text.yellow('Castanea'))
    event.add('bloomingnature:fir_sapling', Text.yellow('Abies'))
    event.add('bloomingnature:fan_palm_sprout', Text.yellow('Livistona'))

    //biomes o plenty
    event.add('biomesoplenty:fir_sapling', Text.yellow('Abies alba'))
    event.add('biomesoplenty:origin_sapling', Text.yellow('Arbor'))
    event.add('biomesoplenty:magic_sapling', Text.yellow('Arbor Magica'))
    event.add('biomesoplenty:dead_sapling', Text.yellow('Arbor Mortuus'))
    event.add('biomesoplenty:palm_sapling', Text.yellow('Arecaceae'))
    event.add('biomesoplenty:rainbow_birch_sapling', Text.yellow('Eucalyptus Deglupta'))
    event.add('biomesoplenty:jacaranda_sapling', Text.yellow('Jacaranda'))
    event.add('biomesoplenty:orange_autumn_sapling', Text.yellow('Liquidambar Styraciflua'))
    event.add('biomesoplenty:yellow_autumn_sapling', Text.yellow('Liriodendron Tulipifera'))
    event.add('biomesoplenty:hellbark_sapling', Text.yellow('Melaleuca Quinquenervia'))
    event.add('biomesoplenty:flowering_oak_sapling', Text.yellow('Quercus Robur'))
    event.add('biomesoplenty:willow_sapling', Text.yellow('Salix'))
    event.add('biomesoplenty:redwood_sapling', Text.yellow('Sequoioideae'))
    event.add('biomesoplenty:snowblossom_sapling', Text.yellow('Styrax Japonicus'))
    event.add('biomesoplenty:mahogany_sapling', Text.yellow('Swietenia'))
    event.add('biomesoplenty:umbran_sapling', Text.yellow('Umbra Arboris'))

    //oh the biomes we've gone
    event.add('biomeswevegone:ironwood_sapling', Text.yellow('Acacia melanoxylon'))
    event.add('biomeswevegone:maple_sapling', Text.yellow('Acer'))
    event.add('biomeswevegone:red_maple_sapling', Text.yellow('Acer rubrum'))
    event.add('biomeswevegone:silver_maple_sapling', Text.yellow('Acer saccharinum'))
})